@startuml
participant Client as ":Client"
participant OfferingsBox as ":Offerings"
participant BookingBox as ":Booking"
participant Admin as ":Administrator"
participant Guardian as ":Legal Guardian"

Client ->> OfferingsBox: searchOfferings()
OfferingsBox -->> Client: list of available offerings

alt Client finds offering of interest
  Client ->> OfferingsBox: selectOffering(offerId)
  OfferingsBox ->> BookingBox: createBooking(offerId, clientId)
  alt Client is underage
    Guardian ->> BookingBox: confirmGuardianship()
    BookingBox -->> Guardian: request confirmation
    Guardian ->> BookingBox: confirm()
  end
  BookingBox -->> Client: bookingConfirmation(bookingId)
  OfferingsBox ->> OfferingsBox: updateOfferingAvailability(offerId)
end

opt Client views bookings
  Client ->> BookingBox: viewBookings(clientId)
  BookingBox -->> Client: list of client bookings
end

opt Client cancels booking
  Client ->> BookingBox: cancelBooking(bookingId)
  BookingBox -->> Client: bookingCancellationConfirmation
  OfferingsBox ->> OfferingsBox: updateOfferingAvailability(offerId)
end

opt Admin views bookings
  Admin ->> BookingBox: viewAllBookings()
  BookingBox -->> Admin: list of all bookings
end

opt Admin cancels booking
  Admin ->> BookingBox: cancelBooking(bookingId)
  BookingBox -->> Admin: bookingCancellationConfirmation
  OfferingsBox ->> OfferingsBox: updateOfferingAvailability(offerId)
end
@enduml